### ISSUE TITLE
Concept is extremely positive - but - I can't seem to get this to work with a WAR in Tomcat - Any working examples?

### ISSUE THREAD

**Issue by MichaelCropper** [cdimascio/dotenv-java#42]

**Comment by cdimascio** [comment]
See the following [maven example](https://github.com/cdimascio/dotenv-java/tree/master/examples%2Fmaven-simple)

**Comment by MichaelCropper** [comment]
Perhaps I should have explained better. The whole point of Environment information is that it is external to your deployable so you can deploy to any environment and the correct environment information is picked up and used. With that maven example, this bundles up the changes inside the build process within the WAR, which is kind of defeating the whole point of managing environment information. 

Perhaps I'm missing something here?

**Comment by cdimascio** [comment]
Hi @MichaelCropper, Note that you should avoid bundling the .env file with your app. (The maven app includes it in the bundle for simplicity so that you don't have to set the env vars. Makes the demonstration simpler but, perhaps is a bit misrepresentative).

Anyway, when you deploy the war, be sure to set the environment variables directly in the environment itself. Dotenv will read the values from the environment. Don't include .env in the war

We may be saying the same thing. If so I'm clearly misunderstanding the question. 

Hope this helps.

**Comment by MichaelCropper** [comment]
It sounds like we are aligned in understanding, perhaps I'm just a little less informed on the dotenv project. 

So, if I've understood properly, basically;

`dotenv.get("MY_ENV")`

is really just a wrapper around;

`System.getEnv("MY_ENV")`

?

i.e. uses actual Operating System Level Environment Variables. Opposed to a similar concept in PHP Laravel framework of a .env file which essentially acts as a basic key=value pair generally stored in the Document Root of a deployed application, with this file not committed to Git etc. 

Or is there something more to it that I'm missing with the dotenv project? 

I guess based on what you've just said... I don't get it. Where is the value add for the dotenv project over an above the out of the box Java stuff? 

I'm trying to see if I can use this in some way and how it compares with other alternatives.
